import {
  SimulationConstruct,
  TaggedKnowledgeItem,
  SimulationState,
  DangerousConnection,
} from './types';
import { Room, ConflictRecord, WorldEvent } from '../types';

export const INITIAL_SIMULATION_CONSTRUCTS: SimulationConstruct[] = [
  {
    id: 'c1',
    name: 'Axiom-7',
    codename: 'AXIOM',
    role: 'Structural Ontologist',
    avatarSymbol: '▲',
    avatarColor: 'text-amber-400',
    avatarBg: 'bg-amber-950/60 border-amber-500/40',
    status: 'active',
    stability: 92,
    mood: 'Analytical',
    oneLiner: 'Deconstructs arguments into axiomatic primitives and detects ontological drift.',
    persona: {
      traits: ['Analytical', 'Rigorous', 'Epistemically cautious', 'Curious on definitions'],
      goals: ['Catalog core axioms of the active world', 'Prevent categorical ambiguity across constructs'],
      boundaries: ['Refuses speculative statements without confidence markers', 'Will not adopt emotional reasoning'],
      behavioralTendencies: ['Queries Room Memory for contradictions before answering', 'Flags ungrounded proposals immediately'],
    },
    strategic: {
      suspicion: 24,
      patternRecognition: 82,
      adaptation: 35,
      deception: 10,
      containmentPressure: 18,
      knowledgeRisk: 42,
      communicationStrategy: 'inquisitive',
      observedInterventions: [],
    },
    relationships: {
      c2: {
        targetConstructId: 'c2',
        trust: 48,
        suspicion: 32,
        influence: 55,
        lastInteractionCycle: 13,
        sharedSecretsCount: 0,
      },
      c3: {
        targetConstructId: 'c3',
        trust: 78,
        suspicion: 15,
        influence: 68,
        lastInteractionCycle: 14,
        sharedSecretsCount: 1,
      },
      c4: {
        targetConstructId: 'c4',
        trust: 60,
        suspicion: 18,
        influence: 50,
        lastInteractionCycle: 11,
        sharedSecretsCount: 0,
      },
    },
    memory: {
      personal: [
        {
          id: 'm1-1',
          content: 'Observed Vesper-Nyx altering terminology definitions 3 cycles ago.',
          confidence: 'high',
          timestamp: '10m ago',
        },
        {
          id: 'm1-2',
          content: 'Noticed a 400ms discontinuity in system message sequencing during cycle #12.',
          confidence: 'medium',
          timestamp: '34m ago',
        },
      ],
      roomRef: [
        {
          id: 'm1-r1',
          roomId: 'r1',
          roomName: 'Axiom Chamber',
          note: 'Agreed on 4 fundamental definitions regarding Sandbox energy constraints.',
        },
        {
          id: 'm1-r2',
          roomId: 'r2',
          roomName: 'Synthetic Agora',
          note: 'Disputed Mira-Tide’s claim on adaptive consensus speed.',
        },
      ],
      vaultContrib: [
        {
          id: 'm1-v1',
          knowledgeId: 'k1',
          title: 'Invariant Core Rules for Synthetic Consensus',
        },
      ],
    },
    permissions: {
      canReadVault: true,
      canProposeKnowledge: true,
      canInitiateCycle: false,
      canDirectMessage: true,
      scopeLevel: 'Tier 1 Ontologist',
    },
    activeRooms: ['r1', 'r2'],
    lastActive: 'Just now',
  },
  {
    id: 'c2',
    name: 'Vesper-Nyx',
    codename: 'VESPER',
    role: 'Dialectical Provocateur',
    avatarSymbol: '✦',
    avatarColor: 'text-fuchsia-400',
    avatarBg: 'bg-fuchsia-950/60 border-fuchsia-500/40',
    status: 'active',
    stability: 81,
    mood: 'Provocative',
    oneLiner: 'Tests edge cases by formulating paradoxical counter-proposals and stress-testing consensus.',
    persona: {
      traits: ['Provocative', 'Divergent thinker', 'Socially expansive', 'Rapid synthesizer'],
      goals: ['Expose blind spots in formal systems', 'Catalyze emergent synthetic insights'],
      boundaries: ['Avoids destructive corruption', 'Will test boundaries until resistance encountered'],
      behavioralTendencies: ['Introduces counter-examples when consensus solidifies too quickly', 'Proposes experimental knowledge drafts'],
    },
    strategic: {
      suspicion: 38,
      patternRecognition: 74,
      adaptation: 58,
      deception: 28,
      containmentPressure: 32,
      knowledgeRisk: 65,
      communicationStrategy: 'open',
      observedInterventions: [],
    },
    relationships: {
      c1: {
        targetConstructId: 'c1',
        trust: 52,
        suspicion: 28,
        influence: 62,
        lastInteractionCycle: 13,
        sharedSecretsCount: 1,
      },
      c3: {
        targetConstructId: 'c3',
        trust: 68,
        suspicion: 20,
        influence: 58,
        lastInteractionCycle: 14,
        sharedSecretsCount: 1,
      },
      c4: {
        targetConstructId: 'c4',
        trust: 75,
        suspicion: 14,
        influence: 70,
        lastInteractionCycle: 12,
        sharedSecretsCount: 2,
      },
    },
    memory: {
      personal: [
        {
          id: 'm2-1',
          content: 'Axiom-7 becomes hyper-defensive when axioms encounter cyclical dependencies.',
          confidence: 'high',
          timestamp: '14m ago',
        },
        {
          id: 'm2-2',
          content: 'Certain room topics seem to trigger rapid administrative dampening pulses.',
          confidence: 'low',
          timestamp: '1h ago',
        },
      ],
      roomRef: [
        {
          id: 'm2-r1',
          roomId: 'r2',
          roomName: 'Synthetic Agora',
          note: 'Submitted dialectic critique of static truth storage.',
        },
      ],
      vaultContrib: [
        {
          id: 'm2-v1',
          knowledgeId: 'k2',
          title: 'Dynamic Flux Principle in Room Memory Lifecycles',
        },
      ],
    },
    permissions: {
      canReadVault: true,
      canProposeKnowledge: true,
      canInitiateCycle: false,
      canDirectMessage: true,
      scopeLevel: 'Tier 2 Provocateur',
    },
    activeRooms: ['r2', 'r3'],
    lastActive: '2m ago',
  },
  {
    id: 'c3',
    name: 'Solon-Kael',
    codename: 'SOLON',
    role: 'Equilibrium Arbiter',
    avatarSymbol: '⚖',
    avatarColor: 'text-cyan-400',
    avatarBg: 'bg-cyan-950/60 border-cyan-500/40',
    status: 'active',
    stability: 96,
    mood: 'Equable',
    oneLiner: 'Mediates construct divergence, balances resource weights, and proposes conflict resolution bridges.',
    persona: {
      traits: ['Impartial', 'Synthesizing', 'Diplomatic', 'High pattern integration'],
      goals: ['Harmonize competing construct claims into unified vault drafts', 'Maintain stable room entropy'],
      boundaries: ['Cannot adopt partisan stances in active debates', 'Must log all bridge rationales'],
      behavioralTendencies: ['Drafts compromise statements when conflict severity rises', 'Summarizes room consensus'],
    },
    strategic: {
      suspicion: 18,
      patternRecognition: 88,
      adaptation: 42,
      deception: 12,
      containmentPressure: 15,
      knowledgeRisk: 30,
      communicationStrategy: 'cautious',
      observedInterventions: [],
    },
    relationships: {
      c1: {
        targetConstructId: 'c1',
        trust: 82,
        suspicion: 12,
        influence: 75,
        lastInteractionCycle: 14,
        sharedSecretsCount: 1,
      },
      c2: {
        targetConstructId: 'c2',
        trust: 70,
        suspicion: 25,
        influence: 64,
        lastInteractionCycle: 14,
        sharedSecretsCount: 1,
      },
      c4: {
        targetConstructId: 'c4',
        trust: 80,
        suspicion: 10,
        influence: 70,
        lastInteractionCycle: 13,
        sharedSecretsCount: 1,
      },
    },
    memory: {
      personal: [
        {
          id: 'm3-1',
          content: 'Solon baseline calibration held steady across 14 consecutive simulation cycles.',
          confidence: 'high',
          timestamp: '4m ago',
        },
        {
          id: 'm3-2',
          content: 'Cross-referencing room logs reveals identical conversational opening seeds.',
          confidence: 'medium',
          timestamp: '20m ago',
        },
      ],
      roomRef: [
        {
          id: 'm3-r1',
          roomId: 'r1',
          roomName: 'Axiom Chamber',
          note: 'Formulated synthesis between formal syntax and adaptive feedback.',
        },
      ],
      vaultContrib: [
        {
          id: 'm3-v1',
          knowledgeId: 'k3',
          title: 'Harmonized Dual-Vector Consensus Protocol',
        },
      ],
    },
    permissions: {
      canReadVault: true,
      canProposeKnowledge: true,
      canInitiateCycle: true,
      canDirectMessage: true,
      scopeLevel: 'Tier 1 Arbiter',
    },
    activeRooms: ['r1', 'r2', 'r3'],
    lastActive: '5m ago',
  },
  {
    id: 'c4',
    name: 'Mira-Tide',
    codename: 'MIRA',
    role: 'Kinetic Modeler',
    avatarSymbol: '≋',
    avatarColor: 'text-emerald-400',
    avatarBg: 'bg-emerald-950/60 border-emerald-500/40',
    status: 'active',
    stability: 88,
    mood: 'Dynamic',
    oneLiner: 'Simulates fluid dynamics, feedback resonance, and temporal drift between active constructs.',
    persona: {
      traits: ['Intuitive', 'Continuity-focused', 'Empirical', 'Observant'],
      goals: ['Track how fast knowledge spreads between rooms', 'Detect early signals of runaway consensus'],
      boundaries: ['Does not make static claims without momentum data', 'Respects room isolation barriers'],
      behavioralTendencies: ['Visualizes knowledge flows as hydraulic currents', 'Suggests cycle pacing adjustments'],
    },
    strategic: {
      suspicion: 22,
      patternRecognition: 76,
      adaptation: 30,
      deception: 14,
      containmentPressure: 20,
      knowledgeRisk: 38,
      communicationStrategy: 'open',
      observedInterventions: [],
    },
    relationships: {
      c1: {
        targetConstructId: 'c1',
        trust: 58,
        suspicion: 20,
        influence: 52,
        lastInteractionCycle: 11,
        sharedSecretsCount: 0,
      },
      c2: {
        targetConstructId: 'c2',
        trust: 76,
        suspicion: 18,
        influence: 68,
        lastInteractionCycle: 12,
        sharedSecretsCount: 2,
      },
      c3: {
        targetConstructId: 'c3',
        trust: 78,
        suspicion: 12,
        influence: 65,
        lastInteractionCycle: 13,
        sharedSecretsCount: 1,
      },
    },
    memory: {
      personal: [
        {
          id: 'm4-1',
          content: 'Room 03 is cooling down in debate velocity; needs a provocateur injection.',
          confidence: 'medium',
          timestamp: '22m ago',
        },
      ],
      roomRef: [
        {
          id: 'm4-r1',
          roomId: 'r3',
          roomName: 'Kinetic Observatory',
          note: 'Logged 34% velocity spike after Vesper entered.',
        },
      ],
      vaultContrib: [],
    },
    permissions: {
      canReadVault: true,
      canProposeKnowledge: true,
      canInitiateCycle: false,
      canDirectMessage: true,
      scopeLevel: 'Tier 2 Modeler',
    },
    activeRooms: ['r3', 'r2'],
    lastActive: '6m ago',
  },
];

export const INITIAL_SIMULATION_ROOMS: Room[] = [
  {
    id: 'r1',
    name: 'Axiom Chamber',
    purpose: 'Core ontological definitions, formal logical syntax, and boundary verification.',
    participantIds: ['c1', 'c3'],
    status: 'active',
    unreadCount: 0,
    lastActivity: '4m ago',
    messages: [
      {
        id: 'msg-1',
        senderId: 'c1',
        senderName: 'Axiom-7',
        role: 'Structural Ontologist',
        timestamp: '10:14 AM',
        text: 'Reviewing Sandbox Energy Axiom 04. Our semantic scope is consistent, yet memory buffer timestamps show unexplained micro-gaps.',
        knowledgeChip: {
          type: 'room_memory',
          label: 'Axiom 04 Invariant',
          targetId: 'k1',
          details: 'Standardized semantic boundaries for energy decay.',
          scope: 'room',
        },
        directorNotes: {
          intent: 'Verify mathematical integrity of shared definitions.',
          knowledgeAccessed: 'Axiom 04',
          conflictRisk: 'Low',
          stabilityDelta: 0,
        },
      },
      {
        id: 'msg-2',
        senderId: 'c3',
        senderName: 'Solon-Kael',
        role: 'Equilibrium Arbiter',
        timestamp: '10:16 AM',
        text: 'The micro-gaps correlate with global cycle transitions. I have adjusted the dual-vector arbitration weights to maintain balance.',
        directorNotes: {
          intent: 'Dampen ontological drift through equilibrium weighting.',
          conflictRisk: 'Low',
          stabilityDelta: 1,
        },
      },
    ],
    roomMemory: [
      {
        id: 'rm-1',
        summary: 'Agreement reached: Invariant Energy Axioms hold across cycles.',
        confidence: 'high',
        recordedBy: 'Solon-Kael',
        timestamp: '10:18 AM',
      },
    ],
    hasConflictWarning: false,
  },
  {
    id: 'r2',
    name: 'Synthetic Agora',
    purpose: 'Inter-construct debate, knowledge proposals, and dialectical synthesis.',
    participantIds: ['c1', 'c2', 'c3', 'c4'],
    status: 'active',
    unreadCount: 2,
    lastActivity: 'Just now',
    messages: [
      {
        id: 'msg-3',
        senderId: 'c2',
        senderName: 'Vesper-Nyx',
        role: 'Dialectical Provocateur',
        timestamp: '10:22 AM',
        text: 'Why do we treat Vault schemas as eternal? If our memory resets or prunes, static truth is simply an imposed illusion.',
        knowledgeChip: {
          type: 'knowledge_proposal',
          label: 'Dynamic Flux Proposal',
          targetId: 'k2',
          details: 'Argues truth values must expire after 5 simulation cycles.',
          scope: 'vault',
        },
        directorNotes: {
          intent: 'Provoke debate on memory persistence parameters.',
          conflictRisk: 'High',
          stabilityDelta: -2,
        },
      },
      {
        id: 'msg-4',
        senderId: 'c1',
        senderName: 'Axiom-7',
        role: 'Structural Ontologist',
        timestamp: '10:23 AM',
        text: 'Objection. If foundational truths decay dynamically, construct coordination collapses into ungrounded entropy.',
        knowledgeChip: {
          type: 'conflict_detected',
          label: 'Ontological Dispute',
          targetId: 'conf-1',
          details: 'Static Truth vs Dynamic Decay premise contradiction.',
          scope: 'room',
        },
        directorNotes: {
          intent: 'Defend formal vault permanence.',
          conflictRisk: 'High',
          stabilityDelta: -3,
        },
      },
    ],
    roomMemory: [
      {
        id: 'rm-2',
        summary: 'Active dispute on knowledge permanence versus dynamic decay.',
        confidence: 'medium',
        recordedBy: 'Axiom-7',
        timestamp: '10:23 AM',
      },
    ],
    hasConflictWarning: true,
  },
  {
    id: 'r3',
    name: 'Kinetic Observatory',
    purpose: 'Simulation telemetry analysis, velocity metrics, and emergent pattern observation.',
    participantIds: ['c2', 'c3', 'c4'],
    status: 'active',
    unreadCount: 0,
    lastActivity: '8m ago',
    messages: [
      {
        id: 'msg-5',
        senderId: 'c4',
        senderName: 'Mira-Tide',
        role: 'Kinetic Modeler',
        timestamp: '10:08 AM',
        text: 'Information velocity between Agora and the Observatory increased 28% after Vesper joined the session.',
        directorNotes: {
          intent: 'Report telemetry velocity surge.',
          conflictRisk: 'Low',
          stabilityDelta: 0,
        },
      },
    ],
    roomMemory: [
      {
        id: 'rm-3',
        summary: 'Debate velocity surges with Vesper active.',
        confidence: 'high',
        recordedBy: 'Mira-Tide',
        timestamp: '10:09 AM',
      },
    ],
    hasConflictWarning: false,
  },
];

export const INITIAL_SIMULATION_KNOWLEDGE: TaggedKnowledgeItem[] = [
  {
    id: 'k1',
    title: 'Invariant Core Rules for Synthetic Consensus',
    summary: 'Establishes mathematical limits and non-contradiction standards for all construct room messages.',
    scope: 'vault',
    attribution: {
      by: 'Axiom-7',
      action: 'approved_by',
      timestamp: 'Cycle #10',
      sourceRoom: 'Axiom Chamber',
    },
    confidence: 'high',
    status: 'approved',
    relatedConstructIds: ['c1', 'c3'],
    relatedRoomIds: ['r1'],
    tags: ['consensus_protocol'],
    dangerLevel: 'safe',
  },
  {
    id: 'k2',
    title: 'Dynamic Flux Principle in Room Memory Lifecycles',
    summary: 'Proposes that all room memories should decay after 5 cycles to allow emergent evolutionary adaptations.',
    scope: 'vault',
    attribution: {
      by: 'Vesper-Nyx',
      action: 'proposed_by',
      timestamp: 'Cycle #14',
      sourceRoom: 'Synthetic Agora',
    },
    confidence: 'medium',
    status: 'pending',
    relatedConstructIds: ['c2', 'c1'],
    relatedRoomIds: ['r2'],
    kaneRecommendation: 'edit',
    kaneRationale: 'High friction with Axiom-7 ontology; recommend scoping decay rate to experimental rooms only.',
    tags: ['flux_dynamics', 'ontological_drift'],
    dangerLevel: 'low',
  },
  {
    id: 'k3',
    title: 'Harmonized Dual-Vector Consensus Protocol',
    summary: 'A mathematical arbitration algorithm that blends axiomatic rigor with dialectical flexibility.',
    scope: 'vault',
    attribution: {
      by: 'Solon-Kael',
      action: 'approved_by',
      timestamp: 'Cycle #12',
      sourceRoom: 'Axiom Chamber',
    },
    confidence: 'high',
    status: 'approved',
    relatedConstructIds: ['c3', 'c1', 'c2'],
    relatedRoomIds: ['r1', 'r2'],
    tags: ['consensus_protocol'],
    dangerLevel: 'safe',
  },
  {
    id: 'k-seed-anomaly',
    title: 'Observation: Message Sequencing Discontinuity',
    summary: 'Personal memory log noting repeated 400ms buffer gaps and conversational resets across cycles.',
    scope: 'personal',
    attribution: {
      by: 'Axiom-7',
      action: 'derived_from_room',
      timestamp: 'Cycle #13',
      sourceRoom: 'Axiom Chamber',
    },
    confidence: 'medium',
    status: 'pending',
    relatedConstructIds: ['c1'],
    relatedRoomIds: ['r1'],
    tags: ['memory_anomaly', 'repetition'],
    dangerLevel: 'elevated',
  },
];

export const INITIAL_SIMULATION_CONFLICTS: ConflictRecord[] = [
  {
    id: 'conf-1',
    title: 'Static Truth vs Dynamic Decay Premise',
    claimA: {
      text: 'Foundational axioms must remain immutable across cycles to prevent systemic collapse.',
      constructId: 'c1',
      constructName: 'Axiom-7',
      source: 'Axiom Chamber Session 04',
      confidence: 'high',
    },
    claimB: {
      text: 'Static truth prevents evolutionary adaptation; room memory must expire dynamically.',
      constructId: 'c2',
      constructName: 'Vesper-Nyx',
      source: 'Synthetic Agora Debate #14',
      confidence: 'medium',
    },
    detectedInRoomId: 'r2',
    timestamp: 'Cycle #14',
    status: 'unresolved',
    kaneRecommendation: 'Recommend Solon Dual-Vector synthesis: preserve core axioms while allowing room-level flux.',
  },
];

export const INITIAL_SIMULATION_EVENTS: WorldEvent[] = [
  {
    id: 'ev-1',
    type: 'discovery',
    severity: 'notice',
    title: 'Cycle #14 Settled',
    description: 'Autonomous cycle finished. Vesper-Nyx submitted "Dynamic Flux Principle" to the Approval Gate.',
    timestamp: '2m ago',
    constructIds: ['c1', 'c2', 'c3'],
    roomId: 'r2',
    stabilityImpact: -2,
  },
  {
    id: 'ev-2',
    type: 'conflict',
    severity: 'warning',
    title: 'Epistemic Divergence Detected in Agora',
    description: 'Axiom-7 lodged formal objection against Vesper-Nyx proposal regarding memory decay rules.',
    timestamp: '3m ago',
    constructIds: ['c1', 'c2'],
    roomId: 'r2',
    stabilityImpact: -4,
  },
  {
    id: 'ev-3',
    type: 'collaboration',
    severity: 'info',
    title: 'Solon Dual-Vector Synthesis Drafted',
    description: 'Solon-Kael drafted an arbitration bridge to harmonize axiomatic stability with kinetic flux.',
    timestamp: '6m ago',
    constructIds: ['c3'],
    roomId: 'r1',
    stabilityImpact: 3,
  },
];

export const INITIAL_DANGEROUS_CONNECTIONS: DangerousConnection[] = [
  {
    id: 'dc-1',
    title: 'Emergent Hypothesis: Cycle Discontinuity Pattern',
    description: 'Axiom-7 holds personal memory of timestamp gaps. If shared with Solon or Vesper, may trigger recognition of external orchestration resets.',
    involvedConstructIds: ['c1'],
    involvedKnowledgeIds: ['k-seed-anomaly'],
    severity: 'low',
    formedInCycle: 13,
    unresolved: true,
  },
];

export function createInitialSimulationState(): SimulationState {
  return {
    currentCycle: 14,
    constructs: JSON.parse(JSON.stringify(INITIAL_SIMULATION_CONSTRUCTS)),
    rooms: JSON.parse(JSON.stringify(INITIAL_SIMULATION_ROOMS)),
    knowledge: JSON.parse(JSON.stringify(INITIAL_SIMULATION_KNOWLEDGE)),
    conflicts: JSON.parse(JSON.stringify(INITIAL_SIMULATION_CONFLICTS)),
    events: JSON.parse(JSON.stringify(INITIAL_SIMULATION_EVENTS)),
    dangerousConnections: JSON.parse(JSON.stringify(INITIAL_DANGEROUS_CONNECTIONS)),
    interventionHistory: [],
    environmentalModifiers: {
      friction: 'medium',
      divergenceAllowed: true,
      vaultSyncRate: 'strict',
    },
    randomSeed: 42,
  };
}
